### ISSUE TITLE
"lack of anti-aliasing (pixelated textures)"

### ISSUE THREAD

**Issue by DEF7** [nkanaev/tipsy#1]
On your readme I think you shouldn't confuse anti-aliasing and texture filtering. The PS1's lack of anti-aliasing isn't why textures are pixelated, that's due to a lack of texture filtering. Each rasterized pixel can only use one texel sample. You can have no anti-aliasing and have smooth filtered textures via bilinear/trilinear texture filtering, which is different from anti-aliasing altogether.

Anti-aliasing pertains to the edges of geometry, allowing a gradiation between "in-polygon" and "outside-polygon" so that you don't just have stair-stepped or "aliased" polygon edges, effectively fading along the edge depending on how much the polygon actually overlaps a pixel.

I would suggest changing the readme text to say something like "no texture filtering (pixelated textures)" and then maybe adding an additional bulletpoint such as "no anti-aliasing (chunky edges)".

**Comment by nkanaev** [comment]
good point. thanks! updated the readme.
