### ISSUE TITLE
request add some assets

### ISSUE THREAD

**Issue by kdridi** [nkanaev/tipsy#3]
I would like to try this project in order to work on it with some students. However, i can't find any obj assets that would be displayable with tipsy. Can you include some of the ones you would use? Some for basic testings and some for a nice rendering.

**Comment by nkanaev** [comment]
*.obj files without *.mtl & textures can be displayed by pressing `W` button to show the wireframe of the model.
the models in the demo were recorded using files from models-resource.com.
i believe there are plenty of resources online that provide sample obj files.

i may consider adding some freely available models, but i'd rather not include copyrighted content from the original psx games.
if anyone could provide assets with the era's aesthetics and permissive license, i'm happy to add them to the repo.
